/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface GenerationRequest {
  'id' : string,
  'status' : ImageStatus,
  'provider' : Provider,
  'errorMessage' : [] | [string],
  'user' : Principal,
  'timestamp' : Time,
  'resultBlob' : [] | [ExternalBlob],
  'prompt' : string,
}
export type ImageStatus = { 'pending' : null } |
  { 'failed' : null } |
  { 'succeeded' : null };
export type Provider = { 'Flux' : null } |
  { 'Dalle3' : null } |
  { 'ReplicateOrProxy' : null } |
  { 'MidJourney' : null } |
  { 'StableDiffusion' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Only authenticated users can create image generation requests.
   */
  'createGenerationRequest' : ActorMethod<[string, Provider], string>,
  'getAllFailedRequests' : ActorMethod<[], Array<GenerationRequest>>,
  'getAllPendingRequests' : ActorMethod<[], Array<GenerationRequest>>,
  'getAllSucceededRequests' : ActorMethod<[], Array<GenerationRequest>>,
  'getAllUserGenerationRequests' : ActorMethod<[], Array<GenerationRequest>>,
  'getCallerGeneratedRequests' : ActorMethod<[], Array<GenerationRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGenerationRequest' : ActorMethod<[string], GenerationRequest>,
  'getUserFailedRequests' : ActorMethod<[Principal], Array<GenerationRequest>>,
  'getUserGenerationRequests' : ActorMethod<
    [Principal],
    Array<GenerationRequest>
  >,
  'getUserPendingRequests' : ActorMethod<[Principal], Array<GenerationRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSucceededRequests' : ActorMethod<
    [Principal],
    Array<GenerationRequest>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateGenerationRequestStatus' : ActorMethod<
    [string, ImageStatus, [] | [ExternalBlob], [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];