/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Provider = IDL.Variant({
  'Flux' : IDL.Null,
  'Dalle3' : IDL.Null,
  'ReplicateOrProxy' : IDL.Null,
  'MidJourney' : IDL.Null,
  'StableDiffusion' : IDL.Null,
});
export const ImageStatus = IDL.Variant({
  'pending' : IDL.Null,
  'failed' : IDL.Null,
  'succeeded' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GenerationRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : ImageStatus,
  'provider' : Provider,
  'errorMessage' : IDL.Opt(IDL.Text),
  'user' : IDL.Principal,
  'timestamp' : Time,
  'resultBlob' : IDL.Opt(ExternalBlob),
  'prompt' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGenerationRequest' : IDL.Func([IDL.Text, Provider], [IDL.Text], []),
  'getAllFailedRequests' : IDL.Func(
      [],
      [IDL.Vec(GenerationRequest)],
      ['query'],
    ),
  'getAllPendingRequests' : IDL.Func(
      [],
      [IDL.Vec(GenerationRequest)],
      ['query'],
    ),
  'getAllSucceededRequests' : IDL.Func(
      [],
      [IDL.Vec(GenerationRequest)],
      ['query'],
    ),
  'getAllUserGenerationRequests' : IDL.Func(
      [],
      [IDL.Vec(GenerationRequest)],
      ['query'],
    ),
  'getCallerGeneratedRequests' : IDL.Func(
      [],
      [IDL.Vec(GenerationRequest)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGenerationRequest' : IDL.Func([IDL.Text], [GenerationRequest], ['query']),
  'getUserFailedRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(GenerationRequest)],
      ['query'],
    ),
  'getUserGenerationRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(GenerationRequest)],
      ['query'],
    ),
  'getUserPendingRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(GenerationRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSucceededRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(GenerationRequest)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateGenerationRequestStatus' : IDL.Func(
      [IDL.Text, ImageStatus, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Provider = IDL.Variant({
    'Flux' : IDL.Null,
    'Dalle3' : IDL.Null,
    'ReplicateOrProxy' : IDL.Null,
    'MidJourney' : IDL.Null,
    'StableDiffusion' : IDL.Null,
  });
  const ImageStatus = IDL.Variant({
    'pending' : IDL.Null,
    'failed' : IDL.Null,
    'succeeded' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GenerationRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : ImageStatus,
    'provider' : Provider,
    'errorMessage' : IDL.Opt(IDL.Text),
    'user' : IDL.Principal,
    'timestamp' : Time,
    'resultBlob' : IDL.Opt(ExternalBlob),
    'prompt' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGenerationRequest' : IDL.Func([IDL.Text, Provider], [IDL.Text], []),
    'getAllFailedRequests' : IDL.Func(
        [],
        [IDL.Vec(GenerationRequest)],
        ['query'],
      ),
    'getAllPendingRequests' : IDL.Func(
        [],
        [IDL.Vec(GenerationRequest)],
        ['query'],
      ),
    'getAllSucceededRequests' : IDL.Func(
        [],
        [IDL.Vec(GenerationRequest)],
        ['query'],
      ),
    'getAllUserGenerationRequests' : IDL.Func(
        [],
        [IDL.Vec(GenerationRequest)],
        ['query'],
      ),
    'getCallerGeneratedRequests' : IDL.Func(
        [],
        [IDL.Vec(GenerationRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGenerationRequest' : IDL.Func(
        [IDL.Text],
        [GenerationRequest],
        ['query'],
      ),
    'getUserFailedRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(GenerationRequest)],
        ['query'],
      ),
    'getUserGenerationRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(GenerationRequest)],
        ['query'],
      ),
    'getUserPendingRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(GenerationRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSucceededRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(GenerationRequest)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateGenerationRequestStatus' : IDL.Func(
        [IDL.Text, ImageStatus, IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };